# Copyright 2026 Knoban LLC. All rights reserved.
#
# This software is confidential and proprietary, intended for use only by
# Knoban LLC or its authorized users. Unauthorized use, copying, modification,
# distribution of this software, or any part of it, is strictly prohibited and
# may be subject to civil and criminal penalties.
#
# A License Agreement is required to view, use, and/or modify this software.
#
# Disclaimer: This software is provided 'as is' and without any express or
# implied warranties. Knoban LLC is not liable for any damages arising out of
# the use of this software.
#
# For inquiries, contact: alden@knoban.com

name: Validate Branch

permissions:
  contents: read

on:
  pull_request:
    branches:
      - develop
  merge_group:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Spellcheck repository
        uses: streetsidesoftware/cspell-action@v7

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Format check
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Type-check
        run: npm run type-check

      - name: Build
        run: npm run build

  validation-outcome:
    needs: [validate]
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Validation Failure
        if: ${{ contains(join(needs.*.result, ','), 'failure') }}
        run: |
          echo "One or more jobs failed."
          exit 1
      - name: Validation Success
        run: echo "All jobs completed successfully."
